import { tool } from "@opencode-ai/plugin"
import { existsSync } from "node:fs"
import { readFile, readdir, unlink } from "node:fs/promises"
import path from "node:path"

function resolveAgentRoot(context: { directory: string }) {
  return context.directory
}

function resolveRunner(context: { directory: string }) {
  return path.join(resolveAgentRoot(context), "agente.py")
}

function resolveArtifactsRoot(context: { directory: string }, datasetName: string) {
  return path.join(resolveAgentRoot(context), "artifacts", datasetName)
}

function ensureInside(base: string, target: string) {
  const relative = path.relative(base, target)
  if (relative.startsWith("..") || path.isAbsolute(relative)) {
    throw new Error("Path escapes the Agente workspace.")
  }
}

async function runRunner(
  context: { directory: string },
  args: string[],
) {
  const runner = resolveRunner(context)
  if (!existsSync(runner)) {
    throw new Error(`Runner not found at ${runner}`)
  }

  const proc = Bun.spawn({
    cmd: ["uv", "run", runner, ...args],
    cwd: resolveAgentRoot(context),
    stdout: "pipe",
    stderr: "pipe",
  })

  const stdout = await new Response(proc.stdout).text()
  const stderr = await new Response(proc.stderr).text()
  const exitCode = await proc.exited

  if (exitCode !== 0) {
    throw new Error(stderr.trim() || stdout.trim() || `Runner failed with exit code ${exitCode}`)
  }

  return JSON.parse(stdout)
}

function normalizeDatasetPath(datasetName: string, datasetPath?: string) {
  if (!datasetPath) {
    return undefined
  }

  const normalized = datasetPath.trim()
  if (!normalized) {
    return undefined
  }

  if (normalized.toLowerCase().endsWith(".csv")) {
    return normalized
  }

  if (datasetName === "penguins") {
    return undefined
  }

  throw new Error(
    "dataset_path must point to a CSV file. Omit it for the built-in 'penguins' dataset.",
  )
}

function asJsonText(payload: unknown) {
  return JSON.stringify(payload, null, 2)
}

export const phase_context = tool({
  description: "Build phase context from local observatory artifacts",
  args: {
    phase: tool.schema
      .enum(["OBSERVE", "DESCRIBE", "HYPOTHESIZE_AND_CONCLUDE"])
      .describe("Current observatory phase"),
    dataset_name: tool.schema
      .string()
      .default("penguins")
      .describe("Dataset identifier used under artifacts/"),
    dataset_path: tool.schema
      .string()
      .optional()
      .describe("Optional CSV path for datasets other than penguins"),
  },
  async execute(args, context) {
    const datasetPath = normalizeDatasetPath(args.dataset_name, args.dataset_path)
    const cliArgs = [
      "context",
      "--phase",
      args.phase,
      "--dataset-name",
      args.dataset_name,
    ]

    if (datasetPath) {
      cliArgs.push("--dataset-path", datasetPath)
    }

    return asJsonText(await runRunner(context, cliArgs))
  },
})

export const execute_phase_plan = tool({
  description: "Execute a planner JSON for the observatory phase",
  args: {
    plan_json: tool.schema
      .string()
      .describe("Strict JSON plan generated by the observatory planner"),
    dataset_name: tool.schema
      .string()
      .default("penguins")
      .describe("Dataset identifier used under artifacts/"),
    dataset_path: tool.schema
      .string()
      .optional()
      .describe("Optional CSV path for datasets other than penguins"),
  },
  async execute(args, context) {
    const datasetPath = normalizeDatasetPath(args.dataset_name, args.dataset_path)
    let parsed: unknown
    try {
      parsed = JSON.parse(args.plan_json)
    } catch (error) {
      throw new Error(`plan_json must be valid JSON: ${String(error)}`)
    }

    const planPath = path.join(resolveAgentRoot(context), ".opencode", "tmp_phase_plan.json")
    await Bun.write(planPath, JSON.stringify(parsed, null, 2))

    const cliArgs = [
      "execute-plan",
      "--plan",
      planPath,
      "--dataset-name",
      args.dataset_name,
    ]

    if (datasetPath) {
      cliArgs.push("--dataset-path", datasetPath)
    }

    try {
      return asJsonText(await runRunner(context, cliArgs))
    } finally {
      await unlink(planPath).catch(() => undefined)
    }
  },
})

export const available_artifacts = tool({
  description: "List available artifacts for a dataset inside this Agente folder",
  args: {
    dataset_name: tool.schema
      .string()
      .default("penguins")
      .describe("Dataset identifier used under artifacts/"),
  },
  async execute(args, context) {
    const artifactsRoot = resolveArtifactsRoot(context, args.dataset_name)
    if (!existsSync(artifactsRoot)) {
      return asJsonText({
        dataset_name: args.dataset_name,
        artifacts_root: artifactsRoot,
        available_artifacts: [],
      })
    }

    const collected: string[] = []

    async function walk(directory: string) {
      const entries = await readdir(directory, { withFileTypes: true })
      for (const entry of entries) {
        const fullPath = path.join(directory, entry.name)
        if (entry.isDirectory()) {
          await walk(fullPath)
          continue
        }
        ensureInside(artifactsRoot, fullPath)
        collected.push(`artifacts/${path.relative(artifactsRoot, fullPath).replaceAll(path.sep, "/")}`)
      }
    }

    await walk(artifactsRoot)

    return asJsonText({
      dataset_name: args.dataset_name,
      artifacts_root: artifactsRoot,
      available_artifacts: collected.sort(),
    })
  },
})

export const read_artifact = tool({
  description: "Read one artifact from this Agente workspace",
  args: {
    dataset_name: tool.schema
      .string()
      .default("penguins")
      .describe("Dataset identifier used under artifacts/"),
    artifact_path: tool.schema
      .string()
      .describe("Artifact path relative to artifacts/, for example 04_descriptive_stats.json"),
  },
  async execute(args, context) {
    const artifactsRoot = resolveArtifactsRoot(context, args.dataset_name)
    const normalized = args.artifact_path.replace(/^artifacts\//, "")
    const artifactPath = path.join(artifactsRoot, normalized)
    ensureInside(artifactsRoot, artifactPath)

    if (!existsSync(artifactPath)) {
      throw new Error(`Artifact not found: artifacts/${normalized}`)
    }

    const extension = path.extname(artifactPath).toLowerCase()
    if (extension === ".json") {
      return asJsonText({
        dataset_name: args.dataset_name,
        artifact_path: `artifacts/${normalized.replaceAll(path.sep, "/")}`,
        content: JSON.parse(await readFile(artifactPath, "utf-8")),
      })
    }

    if (extension === ".md" || extension === ".txt") {
      return asJsonText({
        dataset_name: args.dataset_name,
        artifact_path: `artifacts/${normalized.replaceAll(path.sep, "/")}`,
        content: await readFile(artifactPath, "utf-8"),
      })
    }

    return asJsonText({
      dataset_name: args.dataset_name,
      artifact_path: `artifacts/${normalized.replaceAll(path.sep, "/")}`,
      content: {
        kind: extension || "unknown",
        message: "Binary artifact available. Read the path metadata instead of inline content.",
      },
    })
  },
})
